mysql:
  image: mysql:latest
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
    MYSQL_DATABASE: devops  # Nom de la base de données MySQL
  ports:
    - "3306:3306"  # Mappage du port hôte au port du conteneur MySQL
  volumes:
    - mysql-data:/var/lib/mysql  # Volume pour stocker les données MySQL

  # Spring Boot application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"  # Mappage du port hôte au port du conteneur Spring Boot
    depends_on:
      - mysql  # Dépendance sur le service MySQL
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root  # Nom d'utilisateur de la base de données
      SPRING_DATASOURCE_PASSWORD:   # Mot de passe de la base de données
      
volumes:
  mysql-data:  # Volume pour stocker les données MySQL
