version: '3.8'
services:
  api:
    image: azizsalah07/devopsproject
    container_name: devopsproject
    ports:
      - 8082:8082
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_JSON: '{
          "server.port" : "8082"
          "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/devops?createDatabaseIfNotExist=true"
          "spring.datasource.username" : "root"
          "spring.datasource.password" : "devops"
          "spring.jpa.show-sql" : "true"
          "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    restart: on-failure
  db:
    image: mysql
    container_name: mysqldb
    ports:
      - 3306:3306
    environment:
      - MYSQL_DB=devops
      - MYSQL_ROOT_PASSWORD=devops
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
  adminer:
    image: adminer
    ports:
      - '8089:8080'
    restart: unless-stopped
volumes:
  db: